// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var TestVerifier = artifacts.require('Verifier');
const proof = require('../../zokrates/code/square/proof.json');

contract('TestVerifier', accounts => {
    describe('match erc721 spec', function () {
        beforeEach(async function () { 
            this.contract = await TestVerifier.new({from: account_one});
            // Test verification with correct proof
            // - use the contents from proof.json generated from zokrates steps
            it('should accept correct proof', async function () { 
                let result = await this.contract.verifyTx.call(
                    proof.a,
                    proof.b,
                    proof.c,
                    proof.inputs
                );
                assert.equal(result,true,"should be able to accept correct proof");
            })
                
            // Test verification with incorrect proof
            it('should reject incorrect proof', async function () { 
                let result = await this.contract.verifyTx.call(
                    proof.c,
                    proof.a,
                    proof.b,
                    proof.inputs
                );
                assert.equal(result,false,"should be able to reject incorrect proof");
            })
        })
    })
});
